// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="intersectie_intersectie,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.457500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=13,HLS_VERSION=2020_2}" *)

module intersectie (
        directions,
        semaphores
);


input  [3:0] directions;
output  [1:0] semaphores;

reg[1:0] semaphores;

wire   [3:0] directions_read_read_fu_58_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((directions_read_read_fu_58_p2 == 4'd1) | (directions_read_read_fu_58_p2 == 4'd2) | (directions_read_read_fu_58_p2 == 4'd3) | (directions_read_read_fu_58_p2 == 4'd7) | (directions_read_read_fu_58_p2 == 4'd11))) begin
        semaphores = 2'd1;
    end else if (((directions_read_read_fu_58_p2 == 4'd14) | (directions_read_read_fu_58_p2 == 4'd0) | (directions_read_read_fu_58_p2 == 4'd15) | (directions_read_read_fu_58_p2 == 4'd4) | (directions_read_read_fu_58_p2 == 4'd5) | (directions_read_read_fu_58_p2 == 4'd6) | (directions_read_read_fu_58_p2 == 4'd8) | (directions_read_read_fu_58_p2 == 4'd9) | (directions_read_read_fu_58_p2 == 4'd10) | (directions_read_read_fu_58_p2 == 4'd12) | (directions_read_read_fu_58_p2 == 4'd13))) begin
        semaphores = 2'd2;
    end else begin
        semaphores = 'bx;
    end
end

assign directions_read_read_fu_58_p2 = directions;

endmodule //intersectie
